# Generated by Django 6.0.6 on 2026-08-26 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_mailingattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="mailing.mailing",
            ),
        ),
    ]
