# Generated by Django 6.0.6 on 2026-08-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_alter_mailing_owner_alter_recipient_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
